import type { NextPage } from 'next';
import Head from 'next/head';
import Main from '../components/Main';
import Nav from '../components/Nav';
import Search from '../components/Search';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Github User Search</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <Search />
      <Main />
    </>
  );
};

export default Home;
