import type { NextPage } from 'next';
import Head from 'next/head';
import Body from '../components/Body';
import Nav from '../components/Nav';
import Search from '../components/Search';

const Home: NextPage = () => {
  return (
    <div className='md:flex md:flex-col md:justify-center md:h-screen'>
      <Head>
        <title>Github User Search</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='mx-6 md:mx-24 font-Space'>
        <Nav />
        <Search />
        <Body />
      </div>
    </div>
  );
};

export default Home;
